# Generated by Django 4.0.3 on 2022-03-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('wiki_id', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=35)),
                ('wiki_url', models.URLField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('album_cover', models.URLField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.artist')),
            ],
        ),
    ]
