# Generated by Django 4.0.3 on 2022-04-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_album_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('time_created',)},
        ),
    ]
