# Generated by Django 4.0.3 on 2022-03-11 04:46

import Phonoteque.main_app.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message="This name format won't work.", regex="^([ \\u00c0-\\u01ffa-zA-Z'\\-])+$")])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message="This name format won't work.", regex="^([ \\u00c0-\\u01ffa-zA-Z'\\-])+$")])),
                ('profile_picture', models.ImageField(upload_to='images')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[Phonoteque.main_app.validators.CheckMaxSizeInMb])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], default='Do not show', max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('wiki_id', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=35)),
                ('album_cover', models.URLField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.artist')),
            ],
        ),
    ]
