# Generated by Django 4.0.3 on 2022-03-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='wiki_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
