# Generated by Django 4.0.3 on 2022-03-07 21:12

import Phonoteque.main_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message="This name format won't work.", regex="^([ \\u00c0-\\u01ffa-zA-Z'\\-])+$")])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message="This name format won't work.", regex="^([ \\u00c0-\\u01ffa-zA-Z'\\-])+$")])),
                ('profile_picture', models.ImageField(upload_to='images')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[Phonoteque.main_app.validators.CheckMaxSizeInMb])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], default='Do not show', max_length=11, null=True)),
            ],
        ),
    ]
