# Generated by Django 4.0.3 on 2022-03-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_collection_album_fans_collection_album_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-time_created',)},
        ),
    ]
