# Generated by Django 4.0.3 on 2022-03-12 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_album_resume_album_wiki_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
