# Generated by Django 4.0.3 on 2022-03-18 05:43

import Phonotheque.common_funcs.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message="This name format won't work here, buddy.", regex="^([ \\u00c0-\\u01ffa-zA-Z'\\-])+$")])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message="This name format won't work here, buddy.", regex="^([ \\u00c0-\\u01ffa-zA-Z'\\-])+$")])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[Phonotheque.common_funcs.validators.MaxSizeInMbValidator])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], default='Do not show', max_length=11, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
