# Generated by Django 4.0.3 on 2022-04-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='photo_url',
        ),
    ]
