# Generated by Django 4.0.3 on 2022-04-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_rename_photo_profile_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo_url',
            new_name='photo_URL',
        ),
    ]
