# Generated by Django 4.0.3 on 2022-04-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_rename_photo_url_profile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_URL',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
