# Generated by Django 4.0.3 on 2022-04-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_alter_profile_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
